### ISSUE TITLE
npm translator should mind about optionalDependencies

### ISSUE THREAD

**Issue by kristian** [SAP/ui5-project#51]
## Expected Behavior
The build / serve should not fail in case any `optionalDependencies` are not available.

## Current Behavior
The build fails, due to the module beeing not found.

## Steps to reproduce the issue
Add any optional dependency to the package.json of an NPM project. Try to build / serve.

## Affected components
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [x] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Stack trace/log output
```
[13:51:24] Error: [npm translator] Failed to locate module <anymodule> from <anypath> - Error: Could not locate module <anymodule> via resolve logic (error: Cannot find module '<anymodule>/package.json' from '<anypath>') or in a collection
    at resolveModulePath.then.then.catch.catch (<anypath>\node_modules\@ui5\project\lib\translators\npm.js:219:10)
```

**Comment by RandomByte** [comment]
Interestingly, this is actually caused by the [normalization](https://github.com/npm/normalize-package-data#what-normalization-currently-entails) *("The values in `optionalDependencies` get added to `dependencies`")* done by the [read-pkg-up module](https://github.com/sindresorhus/read-pkg-up) which the npm translator facilitates.

We should check with the `optionalDependencies` map and not fail if those dependencies are not available, just like [npm describes](http://npm.github.io/using-pkgs-docs/package-json/types/optionaldependencies.html).

Thanks for reporting!

**Comment by RandomByte** [comment]
Fix can be tested with UI5 CLI v0.2.4

**Comment by kristian** [comment]
Hey Merlin, for any reason, since the update to v0.2.4 I cannot get `optionalDependencies` NOR `devDependencies` working any longer, they are simply not added to the tree. Anything wrong on our end? Thanks!

**Comment by matz3** [comment]
@kristian, yes that seems to be broken because of https://github.com/SAP/ui5-project/commit/da707d73b5c75b489e2e499de2b4f54924018844#diff-409f83aaa49951469d44c596fda65bc8R48. The if-clause should be negated.

**Comment by kristian** [comment]
@matz3 Thanks for the confirmation! Thought we did something wrong 👍

**Comment by kristian** [comment]
Thanks Matthias!! =)

**Comment by matz3** [comment]
Released as @ui5/cli v0.2.6

**Comment by kristian** [comment]
Working now!! Thanks.
